export const DEFAULT_GIFT_SETTINGS = { enabled:true, giftPriorityEnabled:true, minimumKnownDiamonds:1, unknownValueGiftEligible:true,
  applyTo:"final-only", highlightSeconds:8, notificationSeconds:4, keepAnsweredClosed:true, manualPriorityOverridesGift:true };
const BOOLEANS=new Set(["enabled","giftPriorityEnabled","unknownValueGiftEligible","keepAnsweredClosed","manualPriorityOverridesGift"]);
const INTEGERS={minimumKnownDiamonds:[0,1_000_000_000],highlightSeconds:[0,30],notificationSeconds:[1,15]};
export function validateGiftSettingsPatch(input){if(!input||typeof input!=="object"||Array.isArray(input))throw Error("SETTINGS_OBJECT_REQUIRED");const patch={};for(const[k,v]of Object.entries(input)){if(BOOLEANS.has(k)){if(typeof v!=="boolean")throw Error(`INVALID_SETTING:${k}`)}else if(k in INTEGERS){const[min,max]=INTEGERS[k];if(!Number.isInteger(v)||v<min||v>max)throw Error(`INVALID_SETTING:${k}`)}else if(k==="applyTo"){if(v!=="final-only")throw Error("INVALID_SETTING:applyTo")}else throw Error(`UNKNOWN_SETTING:${k}`);patch[k]=v}return patch}
export function compareGiftPriority(a,b,settings=DEFAULT_GIFT_SETTINGS){const manualFirst=settings.manualPriorityOverridesGift!==false;if(manualFirst){const p=Number(!!b.manualPinned)-Number(!!a.manualPinned);if(p)return p}if(settings.enabled!==false&&settings.giftPriorityEnabled!==false){const g=Number(!!b.giftPriority)-Number(!!a.giftPriority);if(g)return g;if(a.giftPriority&&b.giftPriority){const d=Number(b.giftSummary?.totalDiamonds||0)-Number(a.giftSummary?.totalDiamonds||0);if(d)return d;const t=String(a.giftPriorityAt||"").localeCompare(String(b.giftPriorityAt||""));if(t)return t}}if(!manualFirst){const p=Number(!!b.manualPinned)-Number(!!a.manualPinned);if(p)return p}return(Number(a.priorityRank??a.queueNumber)||Infinity)-(Number(b.priorityRank??b.queueNumber)||Infinity)||(Number(a.queueNumber)||Infinity)-(Number(b.queueNumber)||Infinity)}
export class GiftService{constructor(store){this.store=store;store.gifts||=[];store.giftAttention||=[];store.giftSettings={...DEFAULT_GIFT_SETTINGS,...store.giftSettings}}
 summary(sessionId,userId){const gifts=this.store.gifts.filter(g=>g.sessionId===sessionId&&g.userId===userId),known=gifts.filter(g=>g.valueKnown),latest=[...gifts].sort((a,b)=>String(a.receivedAt).localeCompare(String(b.receivedAt))).at(-1);return{sessionId,userId,giftEventCount:gifts.length,giftQuantity:gifts.reduce((s,g)=>s+Number(g.repeatCount||0),0),totalDiamonds:known.reduce((s,g)=>s+Number(g.totalDiamonds||0),0),valueKnown:known.length===gifts.length,lastGiftId:latest?.giftId||null,lastGiftName:latest?.giftName||null,lastGiftQuantity:latest?.repeatCount||0,lastGiftAt:latest?.receivedAt||null}}
 eligible(summary){const s=this.store.giftSettings;return s.enabled!==false&&s.giftPriorityEnabled!==false&&(summary.valueKnown?summary.totalDiamonds>=s.minimumKnownDiamonds:s.unknownValueGiftEligible)}
 link(sessionId,userId,preferred){const rows=this.store.questionThreads.filter(q=>q.sessionId===sessionId&&q.userId===userId&&!q.answered&&!q.archived&&!q.deleted).sort((a,b)=>a.queueNumber-b.queueNumber),target=preferred?rows.find(q=>q.id===preferred):rows[0],attention=this.attention(sessionId,userId);if(!target)return null;for(const q of rows)if(q.id!==target.id){q.giftPriority=false;q.giftSummary=null;q.giftPriorityAt=null}const summary=this.summary(sessionId,userId);target.giftPriority=this.eligible(summary);target.giftPriorityAt=summary.lastGiftAt;target.giftSummary=summary;if(attention)Object.assign(attention,{hasQuestion:true,linkedQuestionId:target.id,attentionStatus:"linked",updatedAt:new Date().toISOString()});return target}
 attention(sessionId,userId){return this.store.giftAttention.find(a=>a.sessionId===sessionId&&a.userId===userId)}
 receive(gift){if(gift.giftType===1&&!gift.repeatEnd)return{transient:true,gift};if(this.store.gifts.some(g=>g.sessionId===gift.sessionId&&g.id===gift.id))return{duplicate:true};this.store.gifts.push(gift);const summary=this.summary(gift.sessionId,gift.userId);if(this.store.giftSettings.enabled===false)return{gift,summary,attention:null,thread:null};const unanswered=this.store.questionThreads.some(q=>q.sessionId===gift.sessionId&&q.userId===gift.userId&&!q.answered&&!q.archived&&!q.deleted),answered=this.store.questionThreads.some(q=>q.sessionId===gift.sessionId&&q.userId===gift.userId&&q.answered);let a=this.attention(gift.sessionId,gift.userId);if(!a){a={sessionId:gift.sessionId,userId:gift.userId,username:gift.username,nickname:gift.nickname,avatar:gift.avatar,acknowledged:false,acknowledgedAt:null};this.store.giftAttention.push(a)}Object.assign(a,summary,{acknowledged:false,acknowledgedAt:null,hasQuestion:unanswered,attentionStatus:unanswered?"linked":answered?"gift_after_answer":"waiting_question",updatedAt:gift.receivedAt});const thread=unanswered?this.link(gift.sessionId,gift.userId):null;return{gift,summary,attention:a,thread}}
 acknowledge(sessionId,userId,acknowledged=true,now=new Date()){const a=this.attention(sessionId,userId);if(!a)return null;a.acknowledged=acknowledged;a.acknowledgedAt=acknowledged?now.toISOString():null;a.updatedAt=now.toISOString();return a}
}
